#!/usr/bin/env python3
"""Rasterize a monospace TTF into an 8-px-wide, 1-bpp GBA font header.

Emits src/font.h: font[95][CELL_H], glyphs for ASCII 0x20..0x7E, MSB = left.
Run: tools/gen_font.py [size] [yoff]  (defaults tuned for legibility)
Prints an ASCII-art preview to stderr so the glyphs can be eyeballed.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

TTF = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
CELL_W = 8
CELL_H = 12
SIZE = int(sys.argv[1]) if len(sys.argv) > 1 else 13
YOFF = int(sys.argv[2]) if len(sys.argv) > 2 else -1
XOFF = -1
THRESH = 110

font = ImageFont.truetype(TTF, SIZE)
glyphs = []
for code in range(0x20, 0x7F):
    img = Image.new("L", (CELL_W, CELL_H), 0)
    d = ImageDraw.Draw(img)
    d.text((XOFF, YOFF), chr(code), fill=255, font=font)
    rows = []
    for y in range(CELL_H):
        bits = 0
        for x in range(CELL_W):
            if img.getpixel((x, y)) >= THRESH:
                bits |= 1 << (7 - x)
        rows.append(bits)
    glyphs.append(rows)


def preview(s):
    for y in range(CELL_H):
        line = ""
        for ch in s:
            rows = glyphs[ord(ch) - 0x20]
            for x in range(CELL_W):
                line += "#" if (rows[y] >> (7 - x)) & 1 else "."
        sys.stderr.write(line + "\n")


preview("ABCXYZ 0189 SOUNDBIAS")

out = ["/* font.h - 8x%d 1bpp font, ASCII 0x20..0x7E. Generated by gen_font.py */"
       % CELL_H, "#ifndef FONT_H", "#define FONT_H",
       "#define FONT_W 8", "#define FONT_H_PX %d" % CELL_H,
       "static const unsigned char fontdata[95][%d] = {" % CELL_H]
for code, rows in zip(range(0x20, 0x7F), glyphs):
    body = ",".join("0x%02x" % r for r in rows)
    c = chr(code) if chr(code) != '\\' else '\\\\'
    out.append("  {%s}, /* %s */" % (body, c))
out += ["};", "#endif"]
open("src/font.h", "w").write("\n".join(out) + "\n")
sys.stderr.write("\nwrote src/font.h\n")
